// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateGameReducer from "../create_game_reducer";
import InitPopulationReducer from "../init_population_reducer";
import SimulateShotsReducer from "../simulate_shots_reducer";

export type CreateGameParams = __Infer<typeof CreateGameReducer>;
export type InitPopulationParams = __Infer<typeof InitPopulationReducer>;
export type SimulateShotsParams = __Infer<typeof SimulateShotsReducer>;

