// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  championId: __t.u32().primaryKey().name("champion_id"),
  playerId: __t.identity().name("player_id"),
  treeJson: __t.string().name("tree_json"),
  courseVersion: __t.u32().name("course_version"),
  generationsToSolve: __t.u32().name("generations_to_solve"),
});
