// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  genId: __t.u32().primaryKey().name("gen_id"),
  holeId: __t.u32().name("hole_id"),
  genNumber: __t.u32().name("gen_number"),
  phase: __t.string(),
  bestFitness: __t.f64().name("best_fitness"),
  avgFitness: __t.f64().name("avg_fitness"),
  popSize: __t.u32().name("pop_size"),
  playerId: __t.identity().name("player_id"),
});
