// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  genomeId: __t.u32().primaryKey().name("genome_id"),
  genId: __t.u32().name("gen_id"),
  treeJson: __t.string().name("tree_json"),
  treeDepth: __t.u32().name("tree_depth"),
  nodeCount: __t.u32().name("node_count"),
  fitness: __t.f64(),
  origin: __t.string(),
  parentAId: __t.u32().name("parent_a_id"),
  parentBId: __t.u32().name("parent_b_id"),
  isElite: __t.bool().name("is_elite"),
  isSelected: __t.bool().name("is_selected"),
});
