// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  holeId: __t.u32().primaryKey().name("hole_id"),
  par: __t.u32(),
  teeX: __t.f64().name("tee_x"),
  teeZ: __t.f64().name("tee_z"),
  holeX: __t.f64().name("hole_x"),
  holeZ: __t.f64().name("hole_z"),
  distance: __t.f64(),
  windX: __t.f64().name("wind_x"),
  windZ: __t.f64().name("wind_z"),
  courseVersion: __t.u32().name("course_version"),
});
