// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u32().primaryKey().name("event_id"),
  genId: __t.u32().name("gen_id"),
  eventType: __t.string().name("event_type"),
  description: __t.string(),
  genomeIdsJson: __t.string().name("genome_ids_json"),
});
