// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  hofId: __t.u32().primaryKey().name("hof_id"),
  playerId: __t.identity().name("player_id"),
  playerName: __t.string().name("player_name"),
  courseVersion: __t.u32().name("course_version"),
  generationsToSolve: __t.u32().name("generations_to_solve"),
  teeX: __t.f64().name("tee_x"),
  teeZ: __t.f64().name("tee_z"),
  holeX: __t.f64().name("hole_x"),
  holeZ: __t.f64().name("hole_z"),
  windX: __t.f64().name("wind_x"),
  windZ: __t.f64().name("wind_z"),
});
