// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Generation = __t.object("Generation", {
  genId: __t.u32(),
  holeId: __t.u32(),
  genNumber: __t.u32(),
  phase: __t.string(),
  bestFitness: __t.f64(),
  avgFitness: __t.f64(),
  popSize: __t.u32(),
});
export type Generation = __Infer<typeof Generation>;

export const Genome = __t.object("Genome", {
  genomeId: __t.u32(),
  genId: __t.u32(),
  treeJson: __t.string(),
  treeDepth: __t.u32(),
  nodeCount: __t.u32(),
  fitness: __t.f64(),
  origin: __t.string(),
  parentAId: __t.u32(),
  parentBId: __t.u32(),
  isElite: __t.bool(),
  isSelected: __t.bool(),
});
export type Genome = __Infer<typeof Genome>;

export const GolfBall = __t.object("GolfBall", {
  ballId: __t.u32(),
  genomeId: __t.u32(),
  genId: __t.u32(),
  state: __t.string(),
  finalX: __t.f64(),
  finalZ: __t.f64(),
  distanceToHole: __t.f64(),
});
export type GolfBall = __Infer<typeof GolfBall>;

export const GolfCourse = __t.object("GolfCourse", {
  holeId: __t.u32(),
  par: __t.u32(),
  teeX: __t.f64(),
  teeZ: __t.f64(),
  holeX: __t.f64(),
  holeZ: __t.f64(),
  distance: __t.f64(),
  windX: __t.f64(),
  windZ: __t.f64(),
});
export type GolfCourse = __Infer<typeof GolfCourse>;

export const GpEvent = __t.object("GpEvent", {
  eventId: __t.u32(),
  genId: __t.u32(),
  eventType: __t.string(),
  description: __t.string(),
  genomeIdsJson: __t.string(),
});
export type GpEvent = __Infer<typeof GpEvent>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  wildcardGenomeId: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const TrajectoryPoint = __t.object("TrajectoryPoint", {
  pointId: __t.u32(),
  ballId: __t.u32(),
  step: __t.u32(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
});
export type TrajectoryPoint = __Infer<typeof TrajectoryPoint>;

